#!/bin/bash

if [ -z "$1" ]; then
		echo "Must supply username as command line argument"
		exit 0
fi

#remove previous csr structure
rm -rf csr

mkdir csr
cp intermediateopenssl.cnf csr/openssl.cnf

cd csr

mkdir private
chmod 700 private

#create the private key for the csr
openssl genrsa -aes256 -out private/$1.key.pem 2048

chmod 400 private/$1.key.pem

openssl req -config openssl.cnf \
		-key private/$1.key.pem \
		-new -sha256 -out ./$1.pem
